Feature/add entities
Gh0stF1ghter/Project-Rent-n-Ride pull request #12
Opened 2024-06-04 17:04 UTC by Gh0stF1ghter

![image](https://github.com/Gh0stF1ghter/Project-Rent-n-Ride/assets/91743885/be2df6a9-f956-4dcc-ab35-02de73918f52)

2024-06-04 21:07 UTC, pavelGagarin0870 requested changes

2024-06-04 21:07 UTC, pavelGagarin0870 commented on DAL/Entities/VehicleClientHistory.cs
> +﻿namespace DAL.Entities
same

2024-06-05 06:35 UTC, DarPers approved these changes

2024-06-05 07:54 UTC, MaliyOna approved these changes

2024-06-05 11:20 UTC, pavelGagarin0870 approved these changes

2024-06-05 11:43 UTC, merged