feat: add di for repos
Gh0stF1ghter/Project-Rent-n-Ride pull request #35
Opened 2024-06-06 12:35 UTC by Gh0stF1ghter

2024-06-06 12:52 UTC, 5Ka-me requested changes

2024-06-06 12:59 UTC, 5Ka-me requested changes

2024-06-06 12:59 UTC, 5Ka-me commented on API/Program.cs
> +services.AddReposDependencies();
Move your custom DI methods to a separate file, like you did in DAL

2024-06-06 13:47 UTC, 5Ka-me requested changes

2024-06-06 13:47 UTC, 5Ka-me commented on DAL/DI/ServicesConfiguration.cs
> +    }
Make a single entry point to this class

2024-06-06 13:47 UTC, 5Ka-me commented on BLL/DI/ServicesConfiguration.cs
> +        services.AddReposDependencies();
Use single method in a DAL

2024-06-06 13:58 UTC, 5Ka-me commented on DAL/DI/ServicesConfiguration.cs
> +    public static void AddDalDependencies(this IServiceCollection services, IConfiguration configuration)
Perhaps it would be better to name this like "AddDataAccessDependencies"

2024-06-06 13:58 UTC, 5Ka-me approved these changes

2024-06-07 10:19 UTC, DarPers approved these changes

2024-06-07 11:17 UTC, Vlada25 commented on BLL/DI/ServicesConfiguration.cs
> +namespace BLL.DI;
Add empty line after `namespace BLL.DI;` (chtoto na dushnom &#128517;)

2024-06-07 11:18 UTC, Vlada25 commented on BLL/DI/ServicesConfiguration.cs
> +        services.AddDataAccessDependencies(configuration);
I guess you can use arrow function here

2024-06-07 12:38 UTC, MaliyOna approved these changes

2024-06-07 12:39 UTC, merged