Feature/add services to bll
Gh0stF1ghter/Project-Rent-n-Ride pull request #42
Opened 2024-06-07 14:55 UTC by Gh0stF1ghter

2024-06-10 07:09 UTC, MaliyOna approved these changes

2024-06-10 11:15 UTC, 5Ka-me requested changes

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/DI/ServicesConfiguration.cs
> +
Remove empty line

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/DI/ServicesConfiguration.cs
> +        services.AddCustomServicesDependencies();
It would be better to rename this method just smth like "AddServices"

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/DI/ServicesConfiguration.cs
> +        services.AddTransient<IVehicleService, VehicleService>();
Why transient?

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/Services/Interfaces/IManufacturerService.cs
> +    Task UpdateAsync(Guid id, ManufacturerModel newManufacturerModel, CancellationToken cancellationToken);
it would be better if you return updated model instead of Task

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/Services/Interfaces/IModelNameService.cs
> +    Task UpdateAsync(Guid id, ModelNameModel newModelNameModel, CancellationToken cancellationToken);
it would be better if you return updated model instead of Task

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/Services/Interfaces/IVehicleClientHistoryService.cs
> +    Task DeleteAsync(Guid id, CancellationToken cancellationToken);
Why there is "Delete" but no "Update"?

2024-06-10 11:15 UTC, 5Ka-me commented on BLL/Services/Interfaces/IVehicleService.cs
> +    Task UpdateAsync(Guid id, VehicleModel newVehicleModel, CancellationToken cancellationToken);
it would be better if you return updated model instead of Task

2024-06-10 12:50 UTC, 5Ka-me requested changes

2024-06-10 14:21 UTC, 5Ka-me requested changes

2024-06-10 14:21 UTC, 5Ka-me commented on DAL/Repositories/Implementations/ClientRepository.cs
> +>>>>>>> main
Did you saw this?

2024-06-10 14:21 UTC, 5Ka-me commented on DAL/Repositories/Implementations/ManufacturerRepository.cs
> +>>>>>>> main
And this

2024-06-10 14:21 UTC, 5Ka-me commented on DAL/Repositories/Implementations/ModelNameRepository.cs
> +>>>>>>> main
And this

2024-06-10 14:21 UTC, 5Ka-me commented on DAL/Repositories/Implementations/VehicleRepository.cs
> +>>>>>>> main
OMFG

2024-06-11 02:59 UTC, 5Ka-me requested changes
Leave changes only related to the services.
Check all namespaces
Check all usings

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/ClientViewModel.cs
> +namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateClientViewModel.cs
> +﻿namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateManufacturerViewModel.cs
> +﻿namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateModelNameViewModel.cs
> +﻿namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateVchViewModel.cs
> +﻿namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateClientViewModel.cs
> +    Guid VehicleId
What if Client doesn't have anu Vehicle?

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/CreateViewModels/CreateVehicleViewModel.cs
> +namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/ManufacturerViewModel.cs
> +namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/ModelNameViewModel.cs
> +namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/VchViewModel.cs
> +﻿namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 02:59 UTC, 5Ka-me commented on API/ViewModels/VehicleViewModel.cs
> +namespace BLL.ViewModels;
Adjust namespaces

2024-06-11 11:16 UTC, 5Ka-me approved these changes

2024-06-11 11:21 UTC, merged