Create sonarcloud.yml
Gh0stF1ghter/Project-Rent-n-Ride pull request #59
Opened 2024-06-12 11:35 UTC by Gh0stF1ghter

2024-06-12 14:11 UTC, MaliyOna approved these changes

2024-06-13 15:47 UTC, pavelGagarin0870 commented
Test coverage missed

2024-06-13 18:38 UTC, 5Ka-me requested changes
Remove unnecessary comments. Looks like you steal the code from ChatGPT without adjusting 😶‍🌫️
Add code coverage

2024-06-13 18:38 UTC, 5Ka-me commented on .github/workflows/sonarcloud.yml
> +        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
Why there is the ID of an action?

2024-06-16 11:22 UTC, 5Ka-me requested changes

2024-06-16 11:22 UTC, 5Ka-me commented on .github/workflows/sonarcloud.yml
> +        sonarOrganization: gh0stf1ghter
Get these values from GH secrets/variables

2024-06-17 10:03 UTC, 5Ka-me approved these changes

2024-06-17 10:38 UTC, merged